/**
 * GA 커스텀 이벤트 정보
 * [이벤트명]: [한글명, 카테고리]
 */
export const GA_CUSTOM_EVENT_INFO = {
  "app_start": ["앱 시작", "APP"],
  "app_remove": ["앱 삭제", "APP"],
  "app_update": ["앱 업데이트", "APP"],
  "home_main_view": ["홈 메인화면", "홈"],
  "home_profile_ranking_view": ["랭킹 화면", "홈"],
  "home_profile_level_view": ["홈 프로필 레벨 상세보기", "홈"],
  "click_home_membership_ticket": ["홈 상단 이용권 클릭", "홈"],
  "study_main_view": ["학습 메인 화면", "학습"],
  "click_study_item": ["학습 선택 클릭", "학습"],
  "click_study_ads": ["최종 학습 시작", "학습"],
  "click_next_study_quick": ["홈에서 바로 학습하기 클릭", "학습"],
  "click_next_study_ads": ["진행할 학습 최종 학습 클릭", "학습"],
  "next_study_list_view": ["진행할 학습 화면", "학습"],
  "click_next_study_item": ["진행할 학습 선택 클릭", "학습"],
  "study_analytics_view": ["학습 분석 화면", "학습"],
  "downloaded_contents_view": ["소장한 콘텐츠 화면", "학습"],
  "study_manager_view": ["학습 매니저 화면", "학습"],
  "click_study_purchase": ["최종 학습 소장하기 클릭", "학습"],
  "click_next_study_purchase": ["진행할 학습 최종 소장 클릭", "학습"],
  "game_main_view": ["게임 메인 화면", "게임"],
  "game_start": ["게임 시작", "게임"],
  "click_guild_donation": ["길드 기부 클릭", "길드"],
  "guild_join_view": ["길드 가입 화면", "길드"],
  "guild_main_view": ["길드 메인 화면", "길드"],
  "guild_donation_view": ["길드 기부 화면", "길드"],
  "guild_main_building_view": ["길드 본관 화면", "길드"],
  "click_guild_attendance_check": ["길드 출석 체크", "길드"],
  "guild_market_view": ["길드 상점 화면", "길드"],
  "guild_market_purchase": ["길드 상점 상품 구매", "길드"],
  "store_subscription_view": ["스토어 구독권 화면", "결제"],
  "store_goods_view": ["스토어 재화 화면", "결제"],
  "store_study_view": ["스토어 학습 화면", "결제"],
  "store_skin_view": ["스토어 스킨 화면", "결제"],
  "click_store_subscription": ["스토어 구독하기 클릭", "결제"],
  "mail_advertise_view": ["광고 보기 (메일함)", "광고"],
  "mail_advertise_view_receive": ["광고 보상 수령 (메일함)", "광고"],
  "funpik_advertise_view": ["Funpik 광고 화면", "광고"],
  "funpik_advertise_received_reward": ["Funpik 광고 보상 수령", "광고"],
  "load_banner_advertise": ["배너 광고 로드", "광고"],
  "funpik_rewarded_advertise_view": ["Funpik 보상형 광고 화면", "광고"],
  "click_first_purchase_banner": ["첫 구매 선물 배너 클릭", "결제"],
  "click_banner_advertise": ["배너 광고 클릭", "광고"],
  "mail_personal_view": ["개인 메일함 화면", "소통"],
  "mail_all_chat_view": ["전체 채팅 화면", "소통"],
  "mail_guild_chat_view": ["길드 채팅 화면", "소통"],
  "click_send_all_chat": ["전체 채팅 보내기", "소통"],
  "faq_view": ["FAQ 화면", "기타"],
  "click_send_guild_chat": ["길드 채팅 보내기", "소통"],
  "quest_view": ["퀘스트 화면", "퀘스트"],
  "total_quest_receive_reward": ["토탈 퀘스트 보상 수령", "퀘스트"],
  "total_quest_view_advertise": ["토탈 퀘스트 광고 보기", "퀘스트"],
  "total_quest_advertise_receive_reward": ["토탈 퀘스트 광고 보상 수령", "퀘스트"],
  "attendance_view": ["출석 화면", "출석"],
  "attendance_check": ["출석 체크", "출석"],
  "inventory_view": ["가방 화면", "재화"],
  "skin_detail_view": ["스킨 상세보기", "재화"],
  "click_recharge_currency": ["재화 부족 팝업에서 구매하기 클릭", "재화"],
  "closet_view": ["옷장 화면", "재화"],
  "skin_purchase": ["스킨 구매", "재화"],
  "click_skin_detail_go_to_store": ["상점 스킨 구매하러 가기", "재화"],
  "click_skin_detail_go_to_guild": ["길드 스킨 구매하기", "재화"],
  "treasure_draw_view": ["보물 뽑기 화면", "보물"],
  "click_treasure_draw": ["보물 뽑기 클릭", "보물"],
  "treasure_storage_view": ["내 보물함 화면", "보물"],
  "click_treasure_item_strengthen": ["보물 강화하기 클릭", "보물"],
  "click_treasure_draw_ads": ["광고 보고 보물 뽑기 클릭", "보물"],
  "treasure_draw_probability_view": ["보물 뽑기 확률 화면", "보물"],
  "friend_list_view": ["친구 목록 화면", "친구"],
  "click_friend_send_gift": ["친구한테 선물 보내기 클릭", "친구"],
  "click_friend_request": ["친구 신청 클릭", "친구"],
  "friend_add_view": ["친구 추가 화면", "친구"],
  "click_friend_send_gift_all": ["친구 모두 선물 보내기 클릭", "친구"],
  "friend_request_view": ["친구 신청 화면", "친구"],
  "click_friend_intimacy_tooltip": ["홈에서 내 친밀도 툴팁 클릭", "친구"],
  "friend_intimacy_view": ["친구 목록 친밀도 안내 팝업", "친구"],
  "achievements_view": ["업적 화면", "퀘스트"],
  "onboarding_start": ["온보딩 시작", "온보딩"],
  "home_tutorial_start": ["홈 튜토리얼 시작", "온보딩"],
  "tutorial_skip": ["튜토리얼 건너뛰기", "온보딩"],
  "guide_quest_tutorial_start": ["가이드 퀘스트 튜토리얼 시작", "온보딩"],
  "guide_quest_tutorial_finish": ["가이드 퀘스트 튜토리얼 끝까지 완료", "온보딩"],
  "event_view": ["이벤트 화면", "이벤트"],
  "notice_view": ["공지사항 화면", "이벤트"],
  "click_notice_detail": ["공지사항 상세보기 클릭", "이벤트"],
  "click_event_detail": ["이벤트 상세보기 클릭", "이벤트"],
  "setting_main_view": ["설정 메인 화면", "설정"],
  "setting_account_management_view": ["계정 관리 화면", "설정"],
  "setting_language_view": ["언어 설정 화면", "설정"],
  "setting_promotion_code_view": ["프로모션 코드 입력 화면", "설정"],
  "click_setting_subscription_management": ["멤버십 관리 클릭", "설정"],
  "setting_inquiry_view": ["1:1 문의 화면", "설정"],
  "setting_term_of_service_view": ["서비스 이용약관 화면", "설정"],
  "setting_policy_view": ["개인정보 처리방침 화면", "설정"],
  "user_profile_view": ["유저 프로필 화면", "프로필"],
  "click_quick_menu_quest": ["메인 퀵메뉴 퀘스트 클릭", "홈"],
  "click_quick_menu_bag": ["메인 퀵메뉴 가방 클릭", "홈"],
  "click_quick_menu_unit": ["메인 퀵메뉴 소장 클릭", "홈"],
  "click_quick_menu_notice": ["메인 퀵메뉴 공지 클릭", "홈"],
  "click_quick_menu_survival": ["메인 퀵메뉴 서바이벌 클릭", "홈"],
  "click_quick_menu_achievements": ["메인 퀵메뉴 업적 클릭", "홈"],
  "click_quick_menu_closet": ["메인 퀵메뉴 옷장 클릭", "홈"],
  "click_quick_menu_k_info": ["메인 퀵메뉴 K-Life 클릭", "홈"],
  "click_nav_home": ["바텀 네비 홈 클릭", "홈"],
  "click_nav_game": ["바텀 네비 게임 클릭", "홈"],
  "click_nav_study": ["바텀 네비 학습 클릭", "홈"],
  "click_nav_guild": ["바텀 네비 길드 클릭", "홈"],
  "click_nav_store": ["바텀 네비 스토어 클릭", "홈"],
  "click_topik_dday_setting": ["메인 토픽 디데이 설정 클릭", "학습"],
  "click_topik_skill_more": ["메인 토픽 스킬 분석 클릭", "학습"],
  "click_topik_mock_test": ["메인 모의고사 클릭", "학습"],
  "in_app_purchase": ["인앱 결제", "결제"],
  "notification_receive": ["푸시 알림 전송", "푸시"],
  "notification_dismiss": ["푸시 알림 수신 거부", "푸시"],
  "notification_foreground": ["앱 사용 중 푸시 수신", "푸시"],
  "notification_open": ["푸시 알림으로 앱 오픈", "푸시"],
  "screen_view": ["앱 화면 전환", "APP"],
  "session_start": ["앱 세션 참여", "학습"],
  "splash_view_start": ["스플래시 화면 진입", "스플래시"],
  "splash_view_version_update": ["스플래시에서 버전 업데이트 알림", "스플래시"],
  "splash_view_new_user": ["스플래시 -> 온보딩", "스플래시"],
  "splash_view_existing_user": ["스플래시 -> 홈화면", "스플래시"],
  "click_interaction_first_study": ["첫 학습 인터랙션 클릭", "인터랙션"],
  "click_interaction_first_vod": ["첫 VOD 인터랙션 클릭", "인터랙션"],
  "onboarding_step_1_new_user": ["온보딩 신규 클릭", "온보딩"],
  "onboarding_step_2_selected_beginner": ["온보딩 Beginner 선택", "온보딩"],
  "onboarding_step_2_selected_basic": ["온보딩 Basic 선택", "온보딩"],
  "onboarding_step_2_selected_topik": ["온보딩 TOPIK 선택", "온보딩"],
  "click_study_result_next": ["학습 결과 - 다음 학습", "학습"],
  "click_study_result_recommend": ["학습 결과 - 추천 학습", "학습"],
  "click_study_result_topik_explain": ["학습 결과 - TOPIK 해설 보기", "학습"],
  "click_study_result_writing_feedback": ["학습 결과 - TOPIK 쓰기 채점", "학습"],
  "click_study_result_correct_question": ["학습 결과 - 맞춘 문제 자세히 보기", "학습"],
  "click_game_result_retry": ["게임 결과 - 다시 하기", "게임"],
  "click_game_result_recommend": ["게임 결과 - 추천 학습", "게임"],
  "click_k_study_abroad_section": ["K-Life 유학 (Welko)", "K-Life"],
}

