export const IN_APP_ROUTES = [
  { value: 'HOME', label: '홈' },
  { value: 'MAIN', label: '메인' },
  { value: 'SELECT', label: '선택학습 ' },
  { value: 'STUDY', label: '학습' },
  { value: 'GAME', label: '게임' },
  { value: 'MARKET', label: '마켓' },
  { value: 'MARKET_MEMBERSHIP', label: '마켓-멤버십' },
  { value: 'MARKET_GOODS', label: '마켓-상품' },
  { value: 'MARKET_STUDY', label: '마켓-학습' },
  { value: 'MARKET_BOOKS', label: '마켓-교재' },
  { value: 'GUILD', label: '길드' },
  { value: 'RANKING', label: '랭킹' },
  { value: 'MOCKTEST', label: '모의고사' },
  { value: 'MAILBOX', label: '우편함' },
  { value: 'QUEST', label: '퀘스트' },
  { value: 'CLOSET', label: '옷장' },
  { value: 'BAG', label: '가방' },
  { value: 'INVENTORY', label: '인벤토리' },
  { value: 'VOD', label: 'VOD' },
  { value: 'SETTING', label: '설정' },
  { value: 'SETTING_LANG', label: '설정-언어' },
  { value: 'EVENT', label: '이벤트' },
  { value: 'TREASURE', label: '보물' },
  { value: 'FRIENDS', label: '친구-목록' },
  { value: 'FRIENDS_ADD', label: '친구-추가' },
  { value: 'FRIENDS_INVITE', label: '친구-초대' },
  { value: 'TEST', label: '테스트' },
  { value: 'K_LIFE', label: 'K-Life-메인' },
  { value: 'K_LIFE_INFO', label: 'K-Life-정보' },
  { value: 'K_LIFE_PART_TIME', label: 'K-Life-캠페인' },
  { value: 'K_LIFE_FOLLOW_BOOST', label: 'K-Life-팔로워부스터' },
  { value: 'K_LIFE_POST_BOOST', label: 'K-Life-포스트부스터' },
  { value: 'K_LIFE_K_CREATOR', label: 'K-Life-링크플로러' },
  { value: 'WALLET', label: '지갑' },
  { value: 'PURCHASE_DETAIL', label: '결제-상세페이지' },
  { value: 'MEMBERSHIP_BENEFIT', label: '멤버십 보상 메인' },
  { value: 'MEMBERSHIP_REWARD_SIMPLE_VIEW', label: '멤버십 보상 - 상세 화면' },
  { value: 'MEMBERSHIP_REWARD_HANGEUL_NOTE', label: '멤버십 보상 - 한글 쓰기 노트' },
  { value: 'MEMBERSHIP_REWARD_TOPIK_NOTE', label: '멤버십 보상 - TOPIK 쓰기 노트' },
]
